# This file is included in-line in the env section of deployment.yaml
# if .Values.generatedBindings.enabled is true.
- name: WATSON_ASSISTANT_APIKEY
  valueFrom:
    secretKeyRef:
      name: watson-assistant-apikey
      key: apikey
      optional: true
- name: WATSON_ASSISTANT_URL
  valueFrom:
    secretKeyRef:
      name: watson-assistant-url
      key: url
      optional: true
