# This file is included in-line in the env section of deployment.yaml
# if .Values.generatedBindings.enabled is true.
- name: WATSON_ASSISTANT_APIKEY
  valueFrom:
    secretKeyRef:
      name: watson-assistant
      key: apikey
      optional: true
- name: WATSON_ASSISTANT_USERNAME
  valueFrom:
    secretKeyRef:
      name: watson-assistant
      key: username
      optional: true
- name: WATSON_ASSISTANT_PASSWORD
  valueFrom:
    secretKeyRef:
      name: watson-assistant
      key: password
      optional: true
- name: WATSON_ASSISTANT_URL
  valueFrom:
    secretKeyRef:
      name: watson-assistant
      key: url
      optional: true
